-- ImpostorGame / Noite de Jogos
-- Baseline PostgreSQL migration for Supabase.
-- Safe to run more than once in the Supabase SQL Editor.

begin;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke execute on function public.set_updated_at() from public, anon, authenticated;

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  short_description text not null,
  setup_screen text not null,
  card_image_path text,
  modal_image_path text,
  min_players integer,
  max_players integer,
  supports_categories boolean not null default false,
  supports_difficulties boolean not null default false,
  supports_timer boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint games_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint games_min_players_positive check (min_players is null or min_players > 0),
  constraint games_max_players_valid check (
    max_players is null
    or (max_players > 0 and (min_players is null or max_players >= min_players))
  )
);

create table if not exists public.game_tutorials (
  id bigint generated by default as identity primary key,
  game_id bigint not null unique references public.games(id) on delete cascade,
  title text not null,
  copy text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tutorial_steps (
  id bigint generated by default as identity primary key,
  tutorial_id bigint not null references public.game_tutorials(id) on delete cascade,
  step_order integer not null,
  title text not null,
  copy text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tutorial_steps_order_positive check (step_order > 0),
  unique (tutorial_id, step_order)
);

create table if not exists public.role_templates (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.games(id) on delete cascade,
  slug text not null,
  name text not null,
  badge text,
  title text not null,
  description text not null,
  tone text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint role_templates_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint role_templates_sort_order_nonnegative check (sort_order >= 0),
  unique (game_id, slug),
  unique (id, game_id)
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.games(id) on delete cascade,
  slug text not null,
  name text not null,
  content_kind text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint categories_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint categories_content_kind check (
    content_kind in ('secret_word', 'character', 'mimica_word')
  ),
  constraint categories_sort_order_nonnegative check (sort_order >= 0),
  unique (game_id, slug),
  unique (id, game_id)
);

create table if not exists public.difficulties (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.games(id) on delete cascade,
  slug text not null,
  name text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint difficulties_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint difficulties_sort_order_nonnegative check (sort_order >= 0),
  unique (game_id, slug),
  unique (id, game_id)
);

create table if not exists public.content_items (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.games(id) on delete cascade,
  category_id bigint,
  difficulty_id bigint,
  content_kind text not null,
  label text not null,
  normalized_label text not null,
  source_title text,
  source_studio text,
  metadata_json jsonb,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint content_items_category_same_game
    foreign key (category_id, game_id)
    references public.categories(id, game_id)
    on delete restrict,
  constraint content_items_difficulty_same_game
    foreign key (difficulty_id, game_id)
    references public.difficulties(id, game_id)
    on delete restrict,
  constraint content_items_kind check (
    content_kind in ('secret_word', 'character', 'mimica_word')
  ),
  constraint content_items_label_not_blank check (btrim(label) <> ''),
  constraint content_items_normalized_label_not_blank check (btrim(normalized_label) <> ''),
  constraint content_items_sort_order_nonnegative check (sort_order >= 0)
);

create table if not exists public.sessions (
  id uuid primary key default gen_random_uuid(),
  game_id bigint not null references public.games(id) on delete restrict,
  owner_user_id uuid references auth.users(id) on delete set null,
  session_code text unique,
  status text not null default 'draft',
  settings_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint sessions_status check (status in ('draft', 'active', 'finished', 'cancelled')),
  constraint sessions_code_format check (
    session_code is null or session_code ~ '^[A-Z0-9]{6,12}$'
  )
);

create table if not exists public.session_players (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.sessions(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  display_order integer not null,
  nickname text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint session_players_order_nonnegative check (display_order >= 0),
  constraint session_players_nickname_not_blank check (
    nickname is null or btrim(nickname) <> ''
  ),
  unique (session_id, display_order)
);

create table if not exists public.session_assignments (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.sessions(id) on delete cascade,
  session_player_id uuid references public.session_players(id) on delete cascade,
  role_template_id bigint references public.role_templates(id) on delete restrict,
  content_item_id bigint references public.content_items(id) on delete restrict,
  assignment_type text not null,
  assignment_value text not null,
  hidden_metadata_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint session_assignments_type check (
    assignment_type in ('role', 'secret_word', 'character', 'mimica_word')
  ),
  constraint session_assignments_value_not_blank check (btrim(assignment_value) <> '')
);

create index if not exists idx_game_tutorials_game
  on public.game_tutorials(game_id);
create index if not exists idx_tutorial_steps_tutorial
  on public.tutorial_steps(tutorial_id, step_order);
create index if not exists idx_role_templates_game
  on public.role_templates(game_id, sort_order)
  where is_active;
create index if not exists idx_categories_game
  on public.categories(game_id, sort_order)
  where is_active;
create index if not exists idx_difficulties_game
  on public.difficulties(game_id, sort_order)
  where is_active;
create index if not exists idx_content_items_selection
  on public.content_items(game_id, category_id, difficulty_id, sort_order)
  where is_active;
create index if not exists idx_content_items_normalized_label
  on public.content_items(normalized_label);
create index if not exists idx_sessions_game_status
  on public.sessions(game_id, status);
create index if not exists idx_sessions_owner
  on public.sessions(owner_user_id)
  where owner_user_id is not null;
create index if not exists idx_session_players_session
  on public.session_players(session_id, display_order);
create index if not exists idx_session_players_user
  on public.session_players(user_id)
  where user_id is not null;
create index if not exists idx_session_assignments_session
  on public.session_assignments(session_id);
create index if not exists idx_session_assignments_player
  on public.session_assignments(session_player_id)
  where session_player_id is not null;

drop trigger if exists set_games_updated_at on public.games;
create trigger set_games_updated_at
before update on public.games
for each row execute function public.set_updated_at();

drop trigger if exists set_game_tutorials_updated_at on public.game_tutorials;
create trigger set_game_tutorials_updated_at
before update on public.game_tutorials
for each row execute function public.set_updated_at();

drop trigger if exists set_tutorial_steps_updated_at on public.tutorial_steps;
create trigger set_tutorial_steps_updated_at
before update on public.tutorial_steps
for each row execute function public.set_updated_at();

drop trigger if exists set_role_templates_updated_at on public.role_templates;
create trigger set_role_templates_updated_at
before update on public.role_templates
for each row execute function public.set_updated_at();

drop trigger if exists set_categories_updated_at on public.categories;
create trigger set_categories_updated_at
before update on public.categories
for each row execute function public.set_updated_at();

drop trigger if exists set_difficulties_updated_at on public.difficulties;
create trigger set_difficulties_updated_at
before update on public.difficulties
for each row execute function public.set_updated_at();

drop trigger if exists set_content_items_updated_at on public.content_items;
create trigger set_content_items_updated_at
before update on public.content_items
for each row execute function public.set_updated_at();

drop trigger if exists set_sessions_updated_at on public.sessions;
create trigger set_sessions_updated_at
before update on public.sessions
for each row execute function public.set_updated_at();

drop trigger if exists set_session_players_updated_at on public.session_players;
create trigger set_session_players_updated_at
before update on public.session_players
for each row execute function public.set_updated_at();

drop trigger if exists set_session_assignments_updated_at on public.session_assignments;
create trigger set_session_assignments_updated_at
before update on public.session_assignments
for each row execute function public.set_updated_at();

alter table public.games enable row level security;
alter table public.game_tutorials enable row level security;
alter table public.tutorial_steps enable row level security;
alter table public.role_templates enable row level security;
alter table public.categories enable row level security;
alter table public.difficulties enable row level security;
alter table public.content_items enable row level security;
alter table public.sessions enable row level security;
alter table public.session_players enable row level security;
alter table public.session_assignments enable row level security;

revoke all on table public.games from anon, authenticated;
revoke all on table public.game_tutorials from anon, authenticated;
revoke all on table public.tutorial_steps from anon, authenticated;
revoke all on table public.role_templates from anon, authenticated;
revoke all on table public.categories from anon, authenticated;
revoke all on table public.difficulties from anon, authenticated;
revoke all on table public.content_items from anon, authenticated;
revoke all on table public.sessions from anon, authenticated;
revoke all on table public.session_players from anon, authenticated;
revoke all on table public.session_assignments from anon, authenticated;

grant select on table public.games to anon, authenticated;
grant select on table public.game_tutorials to anon, authenticated;
grant select on table public.tutorial_steps to anon, authenticated;
grant select on table public.role_templates to anon, authenticated;
grant select on table public.categories to anon, authenticated;
grant select on table public.difficulties to anon, authenticated;
grant select on table public.content_items to anon, authenticated;

drop policy if exists "Public can read active games" on public.games;
create policy "Public can read active games"
on public.games
for select
to anon, authenticated
using (is_active);

drop policy if exists "Public can read tutorials for active games" on public.game_tutorials;
create policy "Public can read tutorials for active games"
on public.game_tutorials
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.games
    where games.id = game_tutorials.game_id
      and games.is_active
  )
);

drop policy if exists "Public can read tutorial steps for active games" on public.tutorial_steps;
create policy "Public can read tutorial steps for active games"
on public.tutorial_steps
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.game_tutorials
    join public.games on games.id = game_tutorials.game_id
    where game_tutorials.id = tutorial_steps.tutorial_id
      and games.is_active
  )
);

drop policy if exists "Public can read active roles" on public.role_templates;
create policy "Public can read active roles"
on public.role_templates
for select
to anon, authenticated
using (
  is_active
  and exists (
    select 1
    from public.games
    where games.id = role_templates.game_id
      and games.is_active
  )
);

drop policy if exists "Public can read active categories" on public.categories;
create policy "Public can read active categories"
on public.categories
for select
to anon, authenticated
using (
  is_active
  and exists (
    select 1
    from public.games
    where games.id = categories.game_id
      and games.is_active
  )
);

drop policy if exists "Public can read active difficulties" on public.difficulties;
create policy "Public can read active difficulties"
on public.difficulties
for select
to anon, authenticated
using (
  is_active
  and exists (
    select 1
    from public.games
    where games.id = difficulties.game_id
      and games.is_active
  )
);

drop policy if exists "Public can read active content" on public.content_items;
create policy "Public can read active content"
on public.content_items
for select
to anon, authenticated
using (
  is_active
  and exists (
    select 1
    from public.games
    where games.id = content_items.game_id
      and games.is_active
  )
  and (
    category_id is null
    or exists (
      select 1
      from public.categories
      where categories.id = content_items.category_id
        and categories.game_id = content_items.game_id
        and categories.is_active
    )
  )
  and (
    difficulty_id is null
    or exists (
      select 1
      from public.difficulties
      where difficulties.id = content_items.difficulty_id
        and difficulties.game_id = content_items.game_id
        and difficulties.is_active
    )
  )
);

-- No public policies are intentionally created for sessions, players or
-- assignments. Secret roles and round state must remain backend-only until
-- authenticated, ownership-based policies are introduced.

commit;
